sudo: false

language:
    - php
    - node_js

php:
    - 5.6
    - 7.0
    - 7.1

env:
    - WP_VERSION=latest WP_MULTISITE=0

matrix:
    allow_failures:
    - php: 5.6
    - php: 7.1

before_install:
  - mysql -e 'CREATE DATABASE wordpress_test;'

branches:
  only:
    - master
    - develop
    - staging

notifications:
    email: false
