sudo: false

language:
    - php
    - node_js
    - bash

php:
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0 WP_DEVELOP_DIR=/tmp/wordpress-tests-lib

before_install:
    - mysql -e 'CREATE DATABASE wordpress_test;'

before_script:
    - composer config --list --global
    - export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    - composer global require "phpunit/phpunit=5.7.*"
    - composer install
    - bash ./.tests/.bin/install-wp-tests.sh "wordpress_test" "root" ""
    - mv $WP_DEVELOP_DIR/tests/phpunit/includes ./.tests/php

script:
    - phpunit
    - vendor/bin/phpcs --standard=phpcs.ruleset.xml .

branches:
  only:
    - master
    - develop
    - staging

notifications:
    email: false
    slack:
      secure: apfSe2z+zC7eh62FqH9cia0CrXrd9p/232JkUD2WE3dlUJyTkVZ+Y47ham8gPYPjELQjpXXYA2wYdwbVLrIi5CTiNaSRXY7Zcgu4Rn/TvXWAJntmo7AI9VFtHVRvppTeZ5/eZImiRMo2TFhME4fwg5ND7O+7zCbOWh5DZGHPwFylg9UsHpY4iJdyBwdBhchV9rgzHl4AuV7IjX0oqKgVi2RPA+tySZsVLGPHnVoSzGhmiJAgXU2IRS5kjdVG4++o/5lxIevJLKPK7L4gso63hKywUo32Wi7NJfSTg79VFOaJREMF6/nIbr3avTOe+KoGWOYP86K44QRaGlYkTYkm6/t+dUe7+qyEBqvxEw9kcPAxGeTHEW6YDXjLg3kQnnQoRS17TFmZ1KXFDVu4oDvp4+LE9pktrZCjbhqqePsC4xIAjeIrbDp9UDnyzSazZI1THFvWntIDt3xw5/5mdzVBYadYu5WGQgyNs3YY0wiVa8TnJKL/uWJJ7LGN/sDLuthuBxS8lku5hdZMBtY11SuuV3OqRWSYGhrlZZdxh9wwWX7Bexzlhqf+PXjuxt3r9waFTx7iaG7AxlJLx9zcukilYGgUDoZ/1ZiZePOUkG0znUCxzdqqpYqJl82CgQPU5YwIshkE7LQ+1v2Vt2li1VAuXHByZx6ghvoiTGUUCB3DL/c=
      on_success: change
      on_failure: always
