sudo: false

language:
    - php
    - node_js
    - bash

php:
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0 WP_DEVELOP_DIR=/tmp/wordpress-tests-lib

before_install:
    - mysql -e 'CREATE DATABASE wordpress_test;'

before_script:
    - composer config --list --global
    - export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    - composer global require "phpunit/phpunit=5.7.*"
    - composer install
    - bash ./.tests/.bin/install-wp-tests.sh "wordpress_test" "root" ""
    - mv $WP_DEVELOP_DIR/tests/phpunit/includes ./.tests/php

script:
    - phpunit
    - vendor/bin/phpcs --standard=phpcs.ruleset.xml .

branches:
  only:
    - master
    - develop
    - staging

notifications:
    email: false
    slack:
      secure: VNDcqWFeExcv6T9S8Sp8wT6f5AdFLdXVbEhsx3C0zzE6QyMYausbZDsAl+Z221ioS7IN0QEVQJN5P0flIzMnAyjqHyhuvOplEyEyzFiiGPqCPuEuXAUR7dMXOPE77SKAr9ctIaJ2Wk4Z1PtkFd7acMcrDf1B6llXWALniVPlj3S+naMBtGuKo4bgYYyAelTs+A8axs4WE7Iu7j7kEltiowkZ6ZkvUdmqw49cLB6N/7o7wchoXy9C3FieS4NZ3EiwJxfIUTKtWyUUHnYnArLibmCSIbPCMAyWEaSvadhgXL7aw/uXCx5hgld7tbuq/LJ0qpV97tH+sWEJzRMZkwuGeWymUZVNw8u6ekOEoqZaXDxMZzlSE7xyJ06uhvELtzlACgjl+EtBJeu0NIOthLm1LH40Y+brGEibtm/PBQpZDFY+6RKsrw4ChzXUNpkl373Jov9n9w+DJ1tYGHofdb/KZmLSmgsLe/TWjBfikL40z23hfIQU63mpoVDnY7esU9zLxz0uUezTMOq9lNjkIc88qrgC2I1rt6OXNvITN50PBzN96JSgiMkXPFcmk5zCRmJdMyUg2Rr7/mARg0RX/NrYOL8eWhVqa36E27NJiS3gVW7jGPKC760ACBP8DhLO2pF3hRwLgyq0QZ4ZstP75Y+FapLsMBv44bcEXaJPj4VDDNg=
      on_success: change
      on_failure: always
