sudo: false

language:
    - php
    - node_js
    - bash

php:
    - 7.0

env:
    - WP_VERSION=latest WP_MULTISITE=0 WP_DEVELOP_DIR=/tmp/wordpress-tests-lib

before_install:
    - mysql -e 'CREATE DATABASE wordpress_test;'

before_script:
    - composer config --list --global
    - export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
    - composer global require "phpunit/phpunit=5.7.*"
    - composer install
    - bash ./.tests/.bin/install-wp-tests.sh "wordpress_test" "travis" ""
    - mv $WP_DEVELOP_DIR/tests/phpunit/includes ./.tests/php

script:
    - phpunit
    - vendor/bin/phpcs --standard=phpcs.ruleset.xml .

before_deploy:
    - openssl aes-256-cbc -K $encrypted_e1d8b8e0c121_key -iv $encrypted_e1d8b8e0c121_iv -in .travisci/deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa

deploy:
    provider: script
    skip_cleanup: true
    script: .travisci/deploy.sh

branches:
  only:
    - master
    - develop
    - staging

notifications:
    email: false
    slack:
      secure: HtKZvWm3xjuE+ZcRZW0tRBc+oBjSIMEFK/LCNnOQpjiqzM1pb3rO3FAhI5RP3Q6Rz5lQ/zJdZa2TQDgU/bFRALLCsRqugxpGXHh4dMIcsBlihgMXF7DhDubYIy9obCJ4er2uUgKSJKp8sTVW8mAOCl2hVmzBOocx70EqnM+jCl+JkowM+oMBtpCsBfZ4B1y0Tst/ahVMHVkwX/67YqV3oowCBNKWTxlJdGbVvfgPx+v2FZpPGnx0WNLCBIH9UghFnAvIEg3iFZhKD+SjUeVP7+mnJOOVZPq7NH25r29x/GiNvgxjOfRuzunBL6/uiL3iZoKO6znGukVZNIDmHUo52K0kjuM3YQlPJyWDprjJUXtG/yb93FYkbkzcyeBt9vx9H+7Qmw4+GCJ3WInQ8odJ1+xWqfePrMPAx2RtZdX0eyAYiNeW7Bc9/ro9Gjqbm5zVv9QHxZvR1bt2yQzvfEPhylkyXXUqymkhyBsggarOSii2aRSmfwsj7wThTafGGV2HBzz6QjGf9LB1E1OcXkPHcAmRJXlxh5QeL7thxAIEgCjPs5Au+6dQ6lkLNuBDr5RxLPUnrLZSj2l8QoMtf8s4bmTZkrVwMZhFEaPfPhiSB8vTjQIFsJrTm5Kpr6/Fm/MWr8BhWTny/w+KhPBDyElLfelX+48Uri9NS03ZfQCCJ+g=
      on_success: change
      on_failure: always
